import datetime,hashlib,json,pathlib
W=pathlib.Path(__file__).parent;R=pathlib.Path('C:/STOCKS/stocks-predictor');P=R/'docs/open_source_research/OSS-20260911-01'
files={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in P.rglob('*') if p.is_file()}
for name in ['RESEARCH_FREEZE.md','trials.json','trials_v2.json','stocks_predictor/economic_gate.py','stocks_predictor/simulation.py']:
 p=R/name;files[str(p)]=hashlib.sha256(p.read_bytes()).hexdigest()
record={'run_id':'OSS-20260911-01','purpose':'preservation inventory, not a new baseline','observed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':files}
(W/'preservation-before.json').write_text(json.dumps(record,indent=2))
protocol={'run_id':'OSS-20260911-01','experiment':'X03','substudy':'UNC02 diagnostic continuation','prior_receipt':'continuation-v2/controls-receipt.json','seeds':'exactly20260911..20261410, phi0/0.5; no new seeds','budget':'one replay of1000 original series, no substitute estimator,120seconds','checks':['replicate counts462/464/359/462','means from independent innovation weights <=1e-10','finite variance via covariance sum versus forward recursion <=1e-12','production standard error versus independent fsum calculation <=1e-12','boundary versus < does not change counts','exact binomial tails and diagnostic family correction4 tests, preserving original FAIL','normal DGP stationary initial variance, truncation/burn-in audited','paired cross-phi standardized means correlation and outlier overlap'], 'closure':'Close diagnosis if arithmetic, generator and oracle agree within thresholds, counts reproduce, temporal variance mechanism quantitatively reconciles the nested interval changes, and nominal-control deviations receive exact finite-M MonteCarlo tail probabilities. Otherwise stop after this replay as unresolved with failing invariant. No seed search or alternative estimator. A possible random-tail explanation is not proof that PRNG independence is true. Original FAIL remains.','decision':'diagnostic closure is not calibration approval or economic gate; unadjusted criterion retained; family correction is post-hoc diagnosis only','monte_carlo_null':'oracle two-sided P(|Z|<=1.96); iid estimated-sigma expected Student-t503 coverage; 500 replicates, pseudo-independent seeds assumption explicit'}
(W/'X03-G1-diagnostic.json').write_text(json.dumps(protocol,indent=2))
print('Preservation files',len(files),'protocol fixed')
