import hashlib,json,pathlib,statistics
W=pathlib.Path(__file__).parent
x02={'run_id':'OSS-20260911-01','id':'X02','purpose':'Independent small accounting comparisons; no economic certification','external_reference':{'repo':'stefan-jansen/zipline-reloaded','commit':'943010b9da848e317fc520de87edade2b884d329','license':'Apache2 as previously inspected'},'local_reference':{'sha':'80e69daa7d83b3b0f0e3384c53207ee0a9afd5b5','simulation_sha256':'a58cef56caf0e0ac2f555713094c4b6e265ce24164b4bbebbca37226a6d5bad7'},'environment_gate':'BLOCKED: no permitted Linux runner; Python3.13/3.14, full transitive artifact hashes and reviewed adapter required. No installation or CI trigger in this continuation','contract':'integer initial holdings, BRL, raw prices, distinct signal/execute/ex/right/credit/payment/settlement clocks; known inputs only, no margin; output events cash/quantity/receivable/payable/fee/NAV at each clock','tolerance':{'money_brl':.01,'quantity':1e-8,'dates':'exact'},'unsupported':'NOT_DIRECTLY_COMPARABLE; never coerce PASS; compare intersection of supported contracts only','stop':'one pinned configuration per engine,12 cases; stop new engine execution after first unexplained mismatch and preserve full receipt; no tuning;30min2CPU4GB suggested host caps to qualify','cases':[
 {'case':'01 gap','input':'signal price100; next open200; cash1000','oracle':'buy5; cash0; close220 => NAV1100'},
 {'case':'02 fee','input':'buy9 at100; proportional fee1%; cash1000','oracle':'fee9,cash91,quantity9,NAV991 at100'},
 {'case':'03 fixed fee','input':'buy9 at100; fixed2; cash1000','oracle':'fee2,cash98,quantity9,NAV998 at100'},
 {'case':'04 split','input':'10 shares100;2-for-1 split; price50','oracle':'20 shares;NAV1000; no cash'},
 {'case':'05 dividend','input':'10 shares100; ex dividend10/share,price90; payment2days later','oracle':'ex holdings900+receivable100; cash0 until payment; thereaftercash100'},
 {'case':'06 sell after ex','input':'case05 sell10 at90 after ex beforepay','oracle':'right100 retained; sale900 subject separate settlement; finalcash1000'},
 {'case':'07 unknown bar','input':'signal day1, no valid quote day2, first quote100 day3; cash1000','oracle':'no day2 fill; day3 buy10'},
 {'case':'08 stale terminal','input':'held asset missing terminal current quote','oracle':'explicit stale rejection, no silently invented terminalNAV'},
 {'case':'09 bonus','input':'10shares;10%bonus;ex day2,credit day4','oracle':'10 tradable +1 pending untilcredit; no double creation'},
 {'case':'10 fraction','input':'10 shares;1-for-3 reverse split;price300; fraction compensated100 day4','oracle':'3whole shares+1/3 fractional claim worth100; nofraction used totrade beforecash'},
 {'case':'11 unsettled','input':'cash0;sell10at100 settlementday4;buy10at100requestedday3; no credit','oracle':'payable financing not allowed; receivable1000 not freecash untilsettlement'},
 {'case':'12 double count','input':'same dividend as05; adjusted/TR price series also supplied','oracle':'reject ambiguous double-count contract or omit additional cash explicitly; no1100 from an unchanged1000 economic total'}]}
(W/'X02-protocol.json').write_text(json.dumps(x02,indent=2))
x04={'run_id':'OSS-20260911-01','id':'X04','purpose':'Observed return = factor exposure + regression residual - explicit costs, period by period','synthetic_prereg':'120dates,20assets,market alternates±.01,beta=.5+.05*j; orthogonal residual pattern[.002,.002,-.002,-.002];scenario1 zero residual,scenario2 residual plusintercept.001,scenario3 samepluscost.002; fixed before outputs','split':'first60 fit OLS intercept/beta, last60 evaluation, no tuning; equalweights, dates as inference unit','criterion':'gross decomposition error<=1e-12, training fitted beta known<=1e-12, null intercept<=1e-12, plantedintercept.001; scenario3 net belowfactor by.001 onmean; no alpha declaration','market_protocol':'Choose admissible risk-free/factors before returns; normalize units/calendar; y=portfolio excess gross; exposure fitted strictlyintrain, residual outofsample; costs by orders+fixedexpenses; compare equalrisk baseline, sectors,beta,turnover,drawdown; report grossfactor/residual and cost separately; geometrically compounded attribution needs interaction terms, not sums of mean returns','material_exposure_rule':'No alpha label when estimated residual improvement fails frozen net hurdle and temporal confidence criterion even if grossreturn positive; R² descriptive only, residual is not proofalpha','gate':'External/statistical calibration and realdata are separate unmet gates'}
(W/'X04-protocol.json').write_text(json.dumps(x04,indent=2))
results=[];panel=[]
for scenario in [1,2,3]:
 m=[.01*(-1)**t for t in range(120)];port=[]
 for t in range(120):
  returns=[(.5+.05*j)*m[t]+(0 if scenario==1 else .001+[.002,.002,-.002,-.002][t%4]) for j in range(20)];gross=statistics.mean(returns);cost=.002 if scenario==3 else 0;port.append(gross);panel.append({'scenario':scenario,'date_index':t,'factor':m[t],'asset_returns':returns,'gross_portfolio':gross,'cost':cost,'net':gross-cost})
 mx=statistics.mean(m[:60]);my=statistics.mean(port[:60]);beta=sum((x-mx)*(y-my) for x,y in zip(m[:60],port[:60]))/sum((x-mx)**2 for x in m[:60]);alpha=my-beta*mx
 res=[y-beta*x for x,y in zip(m[60:],port[60:])];error=max(abs(y-(beta*x+(y-beta*x))) for x,y in zip(m[60:],port[60:]))
 assert error<1e-12 and abs(beta-.975)<1e-12 and abs(alpha-(0 if scenario==1 else .001))<1e-12
 results.append({'scenario':scenario,'train_beta':beta,'train_intercept':alpha,'test_mean_residual_gross':statistics.mean(res),'test_mean_residual_net':statistics.mean(res)-(.002 if scenario==3 else 0),'decomposition_error':error,'alpha_claim':False})
(W/'X04-synthetic-receipt.json').write_text(json.dumps({'experiment':'X04','protocol_sha256':hashlib.sha256((W/'X04-protocol.json').read_bytes()).hexdigest(),'script_sha256':hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest(),'result':'PASS_ARITHMETIC_ONLY','results':results},indent=2));(W/'X04-fixture.jsonl').write_text(''.join(json.dumps(r)+'\n' for r in panel))
x05={'run_id':'OSS-20260911-01','id':'X05','state':'BLOCKED_DATA_AND_PROTOCOL','executed':False,'arms':['simple admissible equalweight/cash baseline','absolute forecasting with regularized linear regression','simple cross-sectional ranking of a predeclared admissible score','more complex ranking only upon incremental justification; otherwise omitted explicitly'],'comparability':['same decision-available features','same target horizon and nonoverlapping date splits/purge','same historical admissible universe and identities','same cost scenarios and execution assumptions','same capital and risk constraints','same maximum5 configurations per fitted arm, unused budget not transferred; simple deterministic arm has1; all failures recorded'],'metrics':['IC bydate and temporal stability','quantile spreads atsame gross exposure','turnover','gross and neteconomic outcome','factor exposure and residual','risk/drawdown','RMSE as secondary only'],'gates':['X01 usable integrated interval history and eventcoverage','X02 accepted common accounting contract independently checked','X03 temporal inferential method qualified for the actual labels, not merelyUNC02diagnosed','X04 matched factors/costs protocol','lineage6fields+humanreview ifclosedfamily; real reserved split identified before return read'],'capital_authorized':False}
(W/'X05-gates.json').write_text(json.dumps(x05,indent=2));print(json.dumps(results,indent=2))
